### ISSUE TITLE
add stopwords via pod directives

### ISSUE THREAD

**Issue by karenetheridge** [xenoterracide/Dist-Zilla-Plugin-Test-PodSpelling#13]
It would be handy to extract stopwords from the pod itself, similarly to how [PodCoverageTests] extracts subs to skip via "=for Pod::Coverage foo bar baz".  That way plugin bundles don't need to handle a 'stopwords' mvp argument, or dist.inis kept in sync with .pm files -- the pod itself can include the stopword directive.

**Comment by karenetheridge** [comment]
I'm not sure if this is already supported, or how -- e.g. in [@DAGOLDEN] I see

```
=for stopwords autoprereq  ...
```

...but when I add this to my pod it doesn't make it into the spelling test. There doesn't seem to be a podweaver plugin that is at work here... so I'm mystified.

**Comment by xenoterracide** [comment]
I think it's already possible but I'd have to look up the details.

**Comment by karenetheridge** [comment]
Found it...
1. stopwords in pod (via `=for stopwords foo bar`) don't go into the spelling test itself; Pod::Spell sees it and doesn't pass that word upwards to Test::Spelling.
2. the [-Stopwords] Pod::Weaver plugin can gather up several `=for` directives and combine them, also putting them into the `%PodWeaver` stash for other dzil plugins to use
