### ISSUE TITLE
Add CONTRIBUTORS file to explain how/where to patch

### ISSUE THREAD

**Issue by dagolden** [xenoterracide/Dist-Zilla-Plugin-Test-PodSpelling#15]
It's not clear if you want patches on build/master or master, since build/master is the default branch.

Could you please consider adding a CONTRIBUTORS file that clarifies?

Thanks,
David

**Comment by xenoterracide** [comment]
patches should be against master, build/master is a reflection of the 'built' dist. generally speaking patches can be written against built/master that will apply to master so long as people don't modify dzil generated files. This however might be a good excuse for me to revitalize one of my older project which I'd stopped using.

**Comment by xenoterracide** [comment]
would the current state of `build/master` help? I readded SubmittingPatches plugin (new dev version 0.4) feedback on it all welcome

**Comment by dagolden** [comment]
My bad.  The file should be CONTRIBUTING. That's the one that Github gives a link to in the pull request screen.
