### ISSUE TITLE
[DZ] no version was ever set

### ISSUE THREAD

**Issue by hirose31** [xenoterracide/Dist-Zilla-Plugin-Test-PodSpelling#19]
I try to use Test::PodSpelling but error ocuurs.

```
$ mkdir ~/.dzil/profiles/test/
$ echo '[Test::PodSpelling]' > ~/.dzil/profiles/test/profile.ini
$ dzil new -p test Foo

[DZ] making target dir /var/tmp/r/Foo
[DZ] no version was ever set
[DZ] no version was ever set at /usr/local/lib/perl/5.10.1/Moose/Meta/Method/Delegation.pm line 110.
```
- perl 5.10.1 on Linux 
- Dist::Zilla 4.300039
- Dist::Zilla::Plugin::Test::PodSpelling 2.006001
- Moose::Meta::Method::Delegation 2.1005

Could you give me any adivice?

**Comment by xenoterracide** [comment]
You'd have to file a bug with Dist::Zilla in regards to the crappy error... but `Test::PodSpelling` is not a Minter plugin, it would have no function in `profile.ini`. If you're wanting it included in all new modules you should put it in `plugins.ini`. I recommend reading the minting tutorial http://dzil.org/tutorial/minting-profile.html . (this does not appear to be an issue with `Test::PodSpelling`
