### ISSUE TITLE
Who is maintaining this distribution?

### ISSUE THREAD

**Issue by hartzell** [xenoterracide/Dist-Zilla-Plugin-Test-PodSpelling#26]
Hi Xenoterracide,

I have this bit of work, https://github.com/karenetheridge/Dist-Zilla-Plugin-Test-PodSpelling/pull/2, that lets one list stopwords in a file.  Karen hasn't done anything with it and I'm wondering who is authoritative for this distro?

Thanks,

**Comment by xenoterracide** [comment]
I abandoned it long ago, I'm not sure who, if anyone, is maintaining it anymore... Karen is why I quit

**Comment by xenoterracide** [comment]
if Karen hasn't release anything in a long while, and she's not responding you might try to regain it through the abandoned module process through pause, in some weird twist of fate it somehow still belongs to me, I would definitely consent to it being adopted.

**Comment by hartzell** [comment]
Thanks for the info.  I don't want ownership, not doing that much Perl work these days.

I'll see if she responds at some point.
