### ISSUE TITLE
No option to configure additional directories/files to test

### ISSUE THREAD

**Issue by karenetheridge** [xenoterracide/Dist-Zilla-Plugin-Test-PodSpelling#8]
There isn't a way to configure which directories or files are tested - it seems to use bin/ and lib/ only.  Sometimes pod files appear somewhere else, such as the root of the repository, and these files should be tested as well.

**Comment by xenoterracide** [comment]
tuits...

**Comment by karenetheridge** [comment]
it's on my tuit list too, so I may be able to get around to supplying a patch someday.

**Comment by xenoterracide** [comment]
added 2.004
